### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by KonradHoeffner** [schimatos/schimatos.org#16]
The link to <http://schimatos.github.io/> in the readme file redirects to <http://rsmsrv01.nci.org.au:8080/schimatos/>, which results in an "unable to connect" error. I am not using a VPN.

**Comment by srodriguez142857** [comment]
Hi, Konrad.

We are able to access the online demo, which is publicly available.  The
URL is correct: http://rsmsrv01.nci.org.au:8080/schimatos/

[image: image.png]
Perhaps the nature of the error comes from some network settings from your
end?

/$¡rm
Best regards,
Sergio J. Rodríguez M.
https://w3id.org/people/sergio

**Comment by KonradHoeffner** [comment]
The error still persists on my university PC, however it works on my smartphone, so it seems as if this is due to the university firewall on this network, maybe the port 8080 is blocked.
