### ISSUE TITLE
Colour bars for violation

### ISSUE THREAD

**Issue by arminhaller** [schimatos/schimatos.org#3]
Colour bars for violation can be removed and the colours green/yellow/red can be used on the triangle that indicates the violation degree. A tool tip can be included that indicates the level of severity for the property.

**Comment by jeswr** [comment]
To provide context. The colour bars at the top of Form Fields were being used to indicate the `sh:Severity` of the property constraint, rather than indicating whether or not the field passed the validation.

**Comment by jeswr** [comment]
Resolved in commit 080ab9e877278fabbb87fef27b9fdaae38b3aa21
