### ISSUE TITLE
Submit selector

### ISSUE THREAD

**Issue by jaygray0919** [schimatos/schimatos.org#8]
Is the `submit` function working properly? I have configured an item, all configuration areas have a green border, but cannot generate the SHACL code. I toggle the `submit` button, the button blinks, but no result. What am i doing wrong?

**Comment by jeswr** [comment]
Hi,

The `submit` button saves data that you have entered into the form back to the knowledge graph that Schimatos is connected to. To display the code associated to the SHACL you have created/are viewing press the save icon on the bottom panel of the window.

I have created a tutorial on how to create and edit shapes which I will upload in the next few hours, so if you are still running into difficulties that will hopefully help.

**Comment by jeswr** [comment]
I've now uploaded a demo video [here](https://github.com/schimatos/schimatos.org/blob/master/demo_videos/full-demo.mp4). The SHACL saving is at the '12:40' timestamp.
